# Generated by Django 5.1.2 on 2024-11-24 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='https://sun9-45.userapi.com/impg/WzIHXgWw1mCv9FlhBYT3SwuRiX87nQ16yGQ5SA/6wF4X83rUss.jpg?size=384x384&quality=96&sign=4755dd761ff818b1eff4e3e476679a6e&type=album', validators=[django.core.validators.URLValidator])),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('episodes', models.PositiveIntegerField()),
                ('members', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
